server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
       native:
         search-locations: C:/workspace/nutritechv2/config-nutritech/src/main/resources/config